### ISSUE TITLE
[TECH] Use Discord for interaction

### ISSUE THREAD

**Issue by rsletta** [SAP-Inside-Track-Online/sitONLINE-2020#1]
- [x] Create Discord server
- [x] Add base channels
- [x] Add track channels
- [x] Test streaming capabilities 
- [x] Test end to end streaming to YouTube

**Comment by kovboyjder** [comment]
I reckon we should add channels for our tracks

**Comment by rsletta** [comment]
I’m already on it. I will get better at documenting what I’m doing. ☺️

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/11)
