### ISSUE TITLE
SAP Press Books and Espresso tutorial sponsorship

### ISSUE THREAD

**Issue by kovboyjder** [SAP-Inside-Track-Online/sitONLINE-2020#12]

**Comment by kovboyjder** [comment]
Other sponsorship ideas:

- OpenSAP for free activation codes
- SAP Learning hub
- SAP Teched tickets

**Comment by rsletta** [comment]
I can reach out to Clemens and Michaela, to ask for some activation codes. Will wait until things have settled down.

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/22)
