### ISSUE TITLE
### [TECH] Figure out streaming platform

### ISSUE THREAD

**Issue by kovboyjder** [SAP-Inside-Track-Online/sitONLINE-2020#15]
- [ ] We need to be able to host multiple sessions at the same time so people can join in.
- [ ] Be able to invite moderators 
- [ ] Scalable to have the potential of huge numbers of attendees

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/19)
