### ISSUE TITLE
### Add twitter profile - Handle is sapsitonline

### ISSUE THREAD

**Issue by rsletta** [SAP-Inside-Track-Online/sitONLINE-2020#17]

**Comment by kovboyjder** [comment]
Our twitter profile is done https://twitter.com/sapSitOnline

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/3)
