### ISSUE TITLE
Find a new name

### ISSUE THREAD

**Issue by rsletta** [SAP-Inside-Track-Online/sitONLINE-2020#22]
We need to find a new name. Add suggestions in the comments.

**Comment by rsletta** [comment]
World united 24 hour technology bonanza

**Comment by rsletta** [comment]
11000

**Comment by ireps** [comment]
Global SAP Learning Day - 30 May

**Comment by ireps** [comment]
Ultra / Ultramarathon

**Comment by rsletta** [comment]
Stream on!

**Comment by kovboyjder** [comment]
Closed as we are asking the community

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/1)
