### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by kovboyjder** [SAP-Inside-Track-Online/sitONLINE-2020#26]
* [x] twitter
* [x] youtube
* [x] logo
* [x] banner
* [x] social banner
* [ ] blog
* [ ] Google forms
* [x] discord
* [ ] charity page
* [x] bit.ly links
* [x] Github org
* [ ] Github repo + project

**Comment by rsletta** [comment]
@ireps fixes Twitter banner
@rsletta fixes banner

**Comment by rsletta** [comment]
Discord Invite - http://bit.ly/saponlinetrack-discord
Fundraiser
Github Pages - http://bit.ly/saponlinetrack
YouTube - http://bit.ly/saponlinetrack-youtube
Twitter - http://bit.ly/saponlinetrack-twitter

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/12)
