### ISSUE TITLE
### Google Docs for administrative tasks

### ISSUE THREAD

**Issue by rsletta** [SAP-Inside-Track-Online/sitONLINE-2020#4]
- [x] Create gmail account for project  (when name is settled)
- [x] Share with organisers

**Comment by kovboyjder** [comment]
This has been completed, however decided to use github for management

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/9)
