### ISSUE TITLE
[ADMIN] Add blog post and call for speakers

### ISSUE THREAD

**Issue by rsletta** [SAP-Inside-Track-Online/sitONLINE-2020#8]

**Comment by kovboyjder** [comment]
Blog is live: https://blogs.sap.com/2020/02/21/announcing-sap-inside-track-online-in-may-2020/#

**Comment by rsletta** [comment]
Kamino closed and cloned this issue to [SAPOnlineTrack/SAPOnlineTrack-2020](https://github.com/SAPOnlineTrack/SAPOnlineTrack-2020/issues/6)
